# Generated by Django 5.0 on 2024-01-03 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Ordinary Drink', 'Ordinary Drink'), ('Cocktail', 'Cocktail'), ('Shake', 'Shake'), ('Other / Unknown', 'Other / Unknown'), ('Cocoa', 'Cocoa'), ('Shot', 'Shot'), ('Coffee / Tea', 'Coffee / Tea'), ('Homemade Liqueur', 'Homemade Liqueur'), ('Punch / Party Drink', 'Punch / Party Drink'), ('Beer', 'Beer'), ('Soft Drink', 'Soft Drink')], max_length=100)),
                ('IBA', models.CharField(blank=True, max_length=100, null=True)),
                ('alcoholic', models.BooleanField(default=True)),
                ('glass', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('thumbnail_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(blank=True, max_length=100, null=True)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixr.cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixr.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(through='mixr.CocktailIngredient', to='mixr.ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='tags',
            field=models.ManyToManyField(to='mixr.tag'),
        ),
    ]
