# Generated by Django 5.0 on 2024-01-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='IBA',
            field=models.CharField(blank=True, help_text='International Bartenders Association category', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='alcoholic',
            field=models.BooleanField(default=True, help_text='Is the cocktail alcoholic?'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='category',
            field=models.CharField(choices=[('Ordinary Drink', 'Ordinary Drink'), ('Cocktail', 'Cocktail'), ('Shake', 'Shake'), ('Other / Unknown', 'Other / Unknown'), ('Cocoa', 'Cocoa'), ('Shot', 'Shot'), ('Coffee / Tea', 'Coffee / Tea'), ('Homemade Liqueur', 'Homemade Liqueur'), ('Punch / Party Drink', 'Punch / Party Drink'), ('Beer', 'Beer'), ('Soft Drink', 'Soft Drink')], help_text='Category of the cocktail', max_length=100),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='glass',
            field=models.CharField(help_text='Type of glass to serve the cocktail in', max_length=100),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ingredients in the cocktail', through='mixr.CocktailIngredient', to='mixr.ingredient'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='instructions',
            field=models.TextField(help_text='Instructions for making the cocktail'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(help_text='Name of the cocktail', max_length=200),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='tags',
            field=models.ManyToManyField(help_text='Tags describing the cocktail', to='mixr.tag'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='thumbnail_image',
            field=models.URLField(help_text='URL of the thumbnail image for the cocktail'),
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='measurement',
            field=models.CharField(blank=True, help_text='Measurement of the ingredient in the cocktail', max_length=100, null=True),
        ),
    ]
